### ISSUE TITLE
[pm] product planning / 需求收集

### ISSUE THREAD

**Issue by Fatman13** [ipfs-force-community/venus-core-devs#8]
### 新 Sprint 

- [ ] bug bounty，有[赏金](https://github.com/filecoin-project/lotus/pull/11206)？
- [ ] https://filecoinproject.slack.com/archives/CEHTVSEG6/p1692726069836539?thread_ts=1692722289.461299&cid=CEHTVSEG6 (Slack 新人计算 ROI；L1 过重，无法 capture value)

### Sprint 72 之前

- [ ] Bootstrap 节点，是否放在 venushub 一起，帮助 infra 团队达成 bootstrap 节点 okr
- [ ] node provider 负载均衡问题
- [ ] 打包消息过滤器
  - [ ] 参考 Lotus PR 11101
- [ ] lotus 与 venus 产品混用场景
  - [ ] [lotus + lotus-miner + venus-wallet](https://filecoinproject.slack.com/archives/C028PCH8L31/p1689928928173129) 用户注重 venus-wallet 的安全性；
  - [ ] lotus + damocles 用户可以享受执剑人封装效率的提升；
- [ ] DC 续期需求 [slack1](https://filecoinproject.slack.com/archives/CR98WERRN/p1689044871677039)，[slack2](https://filecoinproject.slack.com/archives/CR98WERRN/p1687321510062419)
- [ ] Venus 和 Lotus 兼容需求？Slack [讨论](https://filecoinproject.slack.com/archives/CEHHJNJS3/p1688467850682619) 

### Sprint 65 之前

- [x] #9
- [ ] 水滴引入 boost 的 [LID](https://docs.google.com/presentation/d/19wKalJb_Szdmcc4wIn8aC82ZWXCLJQCwJVKO-3CVXL4/edit#slide=id.g24850f80b4c_0_259)？
- [ ] 4 大文档，[品牌升级](https://github.com/ipfs-force-community/venus-core-devs/issues/3)后，一些更新的收尾工作
- [ ] [集成](https://filecoinproject.slack.com/archives/C04Q63M929Z/p1683788012522799) Lassie 的可能性？
- [x] https://github.com/filecoin-project/venus/issues/5979
- [ ] https://github.com/filecoin-project/venus/issues/5952 （考虑放在 ssm 里面？）
- [ ] https://github.com/filecoin-project/venus/discussions/5957
- [ ] https://github.com/filecoin-project/venus/discussions/5956
- [x] https://github.com/filecoin-project/lotus/issues/10906
- [x] https://github.com/filecoin-project/venus/issues/6023

**Comment by Fatman13** [comment]
暂告一段落。
